### PR TITLE
Fix install.py for macOS 10.15

### PR DESCRIPTION
**Pull request by vdka**
Catalina made has moved Mail.app from /Applications to /System/Applications

### CODE REVIEW

**Comment by xrisk** [comment]
@vdka does this work in Catalina with SIP enabled?

**Comment by vdka** [comment]
Yeah it seemed to work fine for me.

**Comment by konrad-kruczynski** [comment]
Should it work also for Big Sur? I have just tried this branch with no success, any ideas?

**Comment by arachsys** [comment]
Hi. I believe both MailWrap and MailFlow now work correctly on the latest 12.2 and 12.3 releases of mac OS with both python2 and python3 - finally! I've had a couple of success reports, and will try to further improve the documentation to clarify any potential pitfalls as they come up.

**Pull request closed without merging**
